backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
media_folder: public/img
public_folder: img
collections:
  - label: "Hero"
    name: "hero"
    file: "content/hero"
    format: "json"
    fields:
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Headline", name: "headline", widget: "string"}
      - {label: "Subheading", name: "subheading", widget: "string"}
  - label: "Blog"
    name: "blog"
    folder: "content/blog"
    format: "json"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "thumbnail", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}
  - label: "Features"
    name: "features"
    folder: "content/features"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "thumbnail", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}
